name: Debug Windows Build with DuckDB Library

on:
  workflow_dispatch:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Enable Developer Command Prompt (MSVC)
        shell: cmd
        run: |
          echo "Setting environment for Visual Studio..."
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Set Environment Variables
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
          echo "CC=cl.exe" >> $env:GITHUB_ENV

      - name: Build Windows Binary with MSVC
        run: |
          mkdir dist
          go build -o dist/etlx-windows-msvc-amd64.exe ./cmd/main.go

      - name: Upload MSVC Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-binary
          path: dist/*msvc*
 
    