name: Debug Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup MSBuild (for Visual Studio environment)
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Set Environment Variables for CGO
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
#          echo "CC=cl.exe" >> $env:GITHUB_ENV

      - name: Build with MSVC (Visual Studio compiler)
        run: |
          mkdir dist
          go build -o dist/etlx-windows-amd64.exe ./cmd/main.go
          echo "GOARCH=arm64" >> $env:GITHUB_ENV
          go build -o dist/etlx-windows-arm64.exe ./cmd/main.go

      - name: Upload MSVC Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-binary
          path: dist/*windows*

 
    