name: Linux Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ unixodbc unixodbc-dev
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build Linux Binaries
        run: |
          mkdir -p dist
          CGO_ENABLED=0 go build -o dist/etlx-linux-amd64 ./cmd/main.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: dist/*linux*
